export { default as Description } from 'containers/ResultPage2/components/Description';
export { default as ShareResults } from 'containers/ResultPage2/components/ShareResults';
export { default as RecommendationBox } from 'containers/ResultPage2/components/RecommendationBox';
export { default as DiceBox } from 'containers/ResultPage2/components/DiceBox';
export { default as RecipeBox } from 'containers/ResultPage2/components/RecipeBox';
export { default as Section } from 'containers/ResultPage2/components/Section';
export { default as MerchBox } from 'containers/ResultPage2/components/MerchBox';
export { default as BusinessInfo } from 'containers/ResultPage2/components/BusinessInfo';
export { default as Footer } from 'containers/ResultPage2/components/Footer';
